use std::{path::PathBuf, process::Command};

fn main() -> Result<(), ()> {
    let _ = std::fs::create_dir("frontend/src/bindings");
    let mut exports: Vec<_> = std::fs::read_dir("frontend/src/bindings")
        .expect("read dir")
        .filter_map(Result::ok)
        .filter_map(|p| {
            println!("cargo::rerun-if-changed={}", p.path().display());
            p.path()
                .file_stem()
                .map(std::ffi::OsStr::to_str)
                .flatten()
                .map(str::to_owned)
        })
        .filter(|f| f != "index")
        .map(|f| format!("export * from \"./{}\"", f))
        .collect();
    exports.sort();
    let mut file = std::fs::File::create("frontend/src/bindings/index.ts").unwrap();
    std::io::Write::write_all(
        &mut file,
        b"// This file was generated by build.rs. Do not edit this file manually.\n",
    )
    .unwrap();
    std::io::Write::write_all(&mut file, (exports.join(";\n") + ";\n").as_bytes()).unwrap();

    let frontend_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir")).join("frontend");

    for ts in glob::glob(&format!(
        "{}",
        frontend_dir.join("src").join("**").join("*.tsx").display()
    ))
    .expect("glob")
    {
        let ts = ts.expect("glob item");
        println!("cargo::rerun-if-changed={}", ts.display());
    }

    let mut command = if cfg!(target_os = "windows") {
        Command::new("cmd")
    } else {
        Command::new("npm")
    };
    command.current_dir(&frontend_dir);
    if cfg!(target_os = "windows") {
        command.arg("/c").arg("npm ci");
    } else {
        command.arg("ci");
    }
    let output = command.output().expect("npm ci");
    if !output.status.success() {
        eprintln!(
            "stdout: {}",
            std::str::from_utf8(&output.stdout).expect("stdout")
        );
        eprintln!(
            "stderr: {}",
            std::str::from_utf8(&output.stderr).expect("stderr")
        );
        return Err(());
    }

    // uhh
    let mut command = if cfg!(target_os = "windows") {
        Command::new("cmd")
    } else {
        Command::new("./node_modules/.bin/rollup")
    };
    command.current_dir(frontend_dir);
    if cfg!(target_os = "windows") {
        command
            .arg("/c")
            .arg(".\\node_modules\\.bin\\rollup.cmd -c");
    } else {
        command.arg("-c");
    }
    let output = command.output().expect("rollup");

    if !output.status.success() {
        eprintln!(
            "stdout: {}",
            std::str::from_utf8(&output.stdout).expect("stdout")
        );
        eprintln!(
            "stderr: {}",
            std::str::from_utf8(&output.stderr).expect("stderr")
        );
        return Err(());
    }

    Ok(())
}
