[package]
name = 'dart-or-penny'
version = '0.1.0'
edition = '2021'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
black-dwarf = { git = 'https://github.com/zphixon/black-dwarf.git' }
rouille = '3.6.1'
md5-rs = '0.1.5'
anyhow = '1.0.69'
tracing-subscriber = '0.3.16'
tracing = '0.1.34'

[dependencies.image]
version = '0.24.5'
features = ['png', 'tiff', 'bmp', 'gif', 'jpeg']
