[package]
name = "dart-or-penny"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
chrono = "0.4.41"
md5-rs = "0.1.5"
rouille = "3.6.2"
serde = { version = "1.0.219", features = ["derive"] }
tera = "1.20.0"
thiserror = "2.0.12"
toml = "0.8.22"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dependencies.image]
version = "0.25.6"
features = ["png", "tiff", "bmp", "gif", "jpeg"]
