bind = '0.0.0.0:8888'
page_root = '/files'
thumbnail_dir = 'C:/Users/Zack/source/server/dart-or-penny/eg/.dop'
file_dir = 'C:/Users/Zack/Pictures'
thumbnail_size = 75

# shortcuts relative to page_root
[[shortcut]]
name = "Recipes"
url = "dropbox/recipes"
