bind = '0.0.0.0:8888'
page_root = '/files'
thumbnail_dir = 'eg/.dop'
file_dir = 'C:/Users/Zack/Pictures'
thumbnail_size = 75
scan_interval = "30 minutes"

# shortcuts relative to page_root
[[shortcut]]
name = "Recipes"
url = "dropbox/recipes"
