// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PageItem = { basename: string, filename: string, created: string, modified: string, accessed: string, thumbnail_data: string | null, };
