// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";

export type SearchResult = { path: string, kind: ItemKind, };
