// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageItemKind } from "./PageItemKind";

export type PageItem = { kind: PageItemKind, basename: string, filename: string, created: string, modified: string, accessed: string, thumbnail_filename: string | null, };
